### ISSUE TITLE
redux mutations trigger update in firebase.

### ISSUE THREAD

**Issue by walkerrandolphsmith** [hoppula/refire#2]
I have been able to connect my components with react-redux and refire, but I am unsure how to allow redux to manage state mutations and update firebase with newest state. I have considered subscribing to store and sending the (subset) of the store to firebase on changes. I have also considered updating firebase in redux-thunks, but realize that state mutations would be handled in action creators and not reducers. I am trying to accomplish: 

Maintain a set of semantic action creators, reducers handle state mutations, firebase is updated when redux store changes, listen to firebase changes and dispatch the appropriate actions on changes.

Is this library intended to solve updating firebase from local redux store changes?

**Comment by hoppula** [comment]
This library only syncs from Firebase to redux to keep things simple, so you'll have to use the Firebase client's write methods to update the external Firebase state. 

You can also use the [FirebaseWrite](https://github.com/hoppula/refire/blob/master/docs/FirebaseWrite.md) higher order component for mutations, good usage example would be: [ReplyToThread.js in refire-forum](https://github.com/hoppula/refire-forum/blob/master/src/Thread/ReplyToThread.js#L39-L53).

ReplyToThread receives submit method as a prop from FirebaseWrite and the reply data is constructed in [updates.js](https://github.com/hoppula/refire-forum/blob/master/src/updates.js#L63-L83). 

refire automatically syncs data from Firebase after submit for the current user and all other connected users.

**Comment by walkerrandolphsmith** [comment]
Okay thank you for the clarification! Great work.
