### ISSUE TITLE
Compatibility with v3.x

### ISSUE THREAD

**Issue by p0o** [hoppula/refire#3]
Great stuff! Wondering how much is it compatible with the API of Google Firebase v3.x and if there are any plans for that or not?

**Comment by talves** [comment]
Good Question, I am wondering the same thing.

**Comment by hoppula** [comment]
Thanks! 

Currently all the tests depend on [firebase-server](https://github.com/urish/firebase-server) and it [doesn't currently support Firebase API v3](https://github.com/urish/firebase-server/issues/50).

I've been thinking of starting migration to v3 anyways, but I'm currently very busy with other projects. If someone wants to help, PRs are more than welcome. I'll eventually do it myself if needed, but don't expect anything in near future (next month or so).

**Comment by hoppula** [comment]
There's now `next` branch with API v3 support. I haven't published 2.0.0-beta1 to npm yet, but I'll do it soon.

**Comment by urish** [comment]
firebase-server now supports v3

**Comment by hoppula** [comment]
@urish Great news, thanks!

**Comment by prescottprue** [comment]
Been contacting all of the authors of redux-firebase libraries to see if we can work together on a single Defacto solution as it seems like every library is dealing with the v3 update.

Here are just some of the options:
- [refire](https://www.npmjs.com/package/refire) - easily configurable firebase bindings
- [firedux](https://github.com/adjohnson916/firedux) - supports v3.0.4
- [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase) - Current defacto solution but owner is busy for a few months
- [redux-firebase](https://github.com/colbyr/redux-firebase) - best namespace
- [react-firebase](https://github.com/unfold/react-firebase) - Similar to react-redux, good docs

Not sure if everyone here is on the [Firebase Slack](firebase-community.slack.com), but there is a Redux channel there. Might be good to have discussion there so we don't have to leave an issue open in this repo.

**Comment by MrRoyce** [comment]
@prescottprue I would like to join the firebase-community.slack.com but I don't have an id?  Do I need an invitation?

**Comment by hoppula** [comment]
Refire is compatible with Firebase API v3 since 2.0.0.

**Comment by prescottprue** [comment]
@hoppula @MrRoyce @urish @talves @p0o 

I know this issue is closed, but wanted to mention that we are rallying the contributors of redux-firebase libraries in this [redux-firebase gitter](https://gitter.im/redux-firebase/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to discuss possible overlap.

Everyone is welcome!
