### ISSUE TITLE
React-Redux does not satisfy.

### ISSUE THREAD

**Issue by yeongren** [hoppula/refire#7]
Hi, this look really interesting. Thank you for your hard work.

However, while installing, I got the error as below:

npm ERR! peerinvalid The package react-redux@5.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer refire@2.0.3 wants react-redux@^4.4.0

**Comment by hoppula** [comment]
Hi and thanks!

Do you have `react-redux` 5.x installed as regular dependency for your project? refire currently expects `react-redux >= 4.4.0 < 5` as peer dependency. However, I think I'll bump `react-redux` dependency to v5 soon as it's the current major version and its API is identical to v4.

**Comment by yeongren** [comment]
Sure! 

I am using the 5.x for now. 

Alright, will wait for your next update! Thanks for your reply and effort!

**Comment by hoppula** [comment]
React components are now located in [refire-react](https://github.com/hoppula/refire-react) repository and I've updated `react-redux` dependency to 5.x.x.
